version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: testinvoices
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres-data:
  redis_data:

networks:
  backend:
